### ISSUE TITLE
The htcondor python package on PyPI fails to communicate with server with SSL

### ISSUE THREAD

**Issue by gdlmx** [bbockelm/htcondor-python#2]
I find this repo through its PyPI [project page](https://pypi.org/project/htcondor/), hoping its issue  can be posted here. Currently the python package installed from `pip` is linked with `libcrypto.so.0.9.8`: 

    $ ldd htcondor/_htcondor.so
        libcrypto-de69073a.so.0.9.8e => /tmp/condor/htcondor/.libs/libcrypto-de69073a.so.0.9.8e (0x00007f1e9637d000)

However, the official binaries (available at research.cs.wisc.edu/htcondor) are linked with a newer (and incompatible) version `libcrypto.so.10`:

    $ ldd /usr/bin/condor_q
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f68b49c7000)

It is known that OpenSSL libraries are not backwards compatible.
As a result, the python client installed from `pip` will fail to communicate with the "official" HTCondor server if SSL is enforced. The user will get the error message "OSError: Failed communication with collector". This problem has been discovered on CentOS7 with the following version:

Server:

    $CondorVersion: 8.6.10 Mar 12 2018 BuildID: 435200 $
    $CondorPlatform: x86_64_RedHat7 $

Client:

    htcondor-8.7.7-cp36-cp36m-manylinux1_x86_64.whl

**Comment by jasoncpatton** [comment]
Thank you for bringing this to our attention! This repository is not followed by the HTCondor team  that is actively developing the python bindings -- see https://github.com/htcondor/htcondor/tree/master/src/python-bindings . I've appended this issue [to a ticket](https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6692) on our local bugtracker. We prefer to handle user feedback via the [htcondor-users email list](https://lists.cs.wisc.edu/mailman/listinfo/htcondor-users), but you're also welcome to copy this ticket over to the [htcondor repo](https://github.com/htcondor/htcondor) and I can keep in touch there.

The issue with libcrypto being out of date is from our failure to keep up with updating our manylinux docker image that we used to build the wheels for PyPI. I've targeted the next release, 8.7.9, to get this fixed, and I will release an update to the 8.7.8 wheels on PyPI (with a notice here and on htcondor-users) if it can be fixed sooner.

Hopefully using the official packages is an acceptable workaround in the meantime. I realize the drawbacks are that you're stuck (on CentOS 7) using Python 2 and that you must install the entire htcondor package.
